name: elderdc
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: 'Gordon D. Elder, DC, Inc'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1c2c65'
    - '#000000'
    - '#8a0031'
    - '#cecece'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
