name: elderdc
favicon: null
layout_spectrum: 0.9505395132582635
typography_spectrum: 0.10141179990023375
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1c2c65'
    - '#000000'
    - '#8a0031'
    - '#cecece'
  brandStrength: 0.32835472002625465
  lightness: 0.038770105224102736
  saturation: 0.30415123980492353
  rhythmicContrast: 0.5278330373112112
purpose: []
